### ISSUE TITLE
Needs changelog

### ISSUE THREAD

**Issue by estk** [mikedilger/buf-read-ext#2]
Without a changelog, its really hard to know if its ok to update this crate.

**Comment by mikedilger** [comment]
That's fair. I'll work on that soon.

Until then, the only change of significance is that I've removed the broken async code (it blocks; async code shouldn't block). I regret ever publishing the async code - it was a mistake on my part due to switching between different things and forgetting where I left things off.

If you utilise the async code and it seems to work well enough in your case, don't upgrade to 0.4, but perhpas plan to migrate to the sync code.  If you need an async version, let me know and I'll bump the priority. Also I could use help developing one.

**Comment by mikedilger** [comment]
fixed in 61abb0be7fbd8a891689e6e27685d89155d85aa1
